version: "3.8"
services:
  backend:
    build:
      context: ./candidate_profiles/
    volumes:
      - ./candidate_profiles/:/usr/src/candidate_profiles/
    ports:
      - 8000:8000
    image: candidate_profiles:Elevatus
    container_name: candidate_profiles_container
    env_file:
      - env-vars.env